version: '3.3'
services:
  traefik:
    container_name: traefik
    image: traefik:v2.3
    command:
    - --api.insecure=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --entrypoints.web.address=:80
    ports:
    - 80:80
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  dokuwiki-2020-07-29: ./core_engines/dokuwiki-2020-07-29
