services:
  dokuanimal:
    build: .
    container_name: dokuanimal
    environment:
      engine_version: dokuwiki-2020-07-29
    labels:
    - traefik.enable=true
    - traefik.http.routers.dokuanimal.rule=Host(`dokuanimal.localhost`)
    - traefik.http.routers.dokuanimal.entrypoints=web
    volumes:
    - ./core_engines/dokuwiki-2020-07-29:/var/www/html:ro
    - ./wikis_data/dokuanimal/conf:/var/www/html/conf:rw
    - ./wikis_data/dokuanimal/data:/var/www/html/data:rw
  test:
    build: .
    container_name: test
    environment:
      engine_version: dokuwiki-2020-07-29
    labels:
    - traefik.enable=true
    - traefik.http.routers.test.rule=Host(`test.localhost`)
    - traefik.http.routers.test.entrypoints=web
    volumes:
    - ./core_engines/dokuwiki-2020-07-29:/var/www/html:ro
    - ./wikis_data/test/conf:/var/www/html/conf:rw
    - ./wikis_data/test/data:/var/www/html/data:rw
  traefik:
    command:
    - --api.insecure=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --entrypoints.web.address=:80
    container_name: traefik
    image: traefik:v2.3
    ports:
    - 80:80
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
version: '3.3'
