# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 13 Nov 2020 10:25:16 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

dasdas:$2y$10$B5tEc7wvu5bX1x9XfSkIGOnE3lJRYNRFQqWwSNMBf9gf3Kpr5UNlq:dasdas:dsada2@dada:admin,user
